// P1 Checkpoint 3: candidate review and export UI.
function readAnkiCandidates(){const value=readJson(ankiCandidatesKey,[]);return Array.isArray(value)?value:[];}
function saveAnkiCandidates(records,operation="p1-save-anki"){const before=readRawStorageSnapshot();applyStorageSnapshotTransaction({...before,[ankiCandidatesKey]:JSON.stringify(records)},operation,false);}
function createAnkiCandidate(input){const outcome=upsertAnkiCandidate(readAnkiCandidates(),input);saveAnkiCandidates(outcome.records);return outcome.record;}
function generateTodayAnkiCandidates(){const professional={};["722","844"].forEach(subject=>{professional[subject]=getProfessionalUnits(getDateKey(),subject).map(unit=>({...unit,subject}));});const generated=generateAnkiCandidatesFromSources({records:readAnkiCandidates(),date:getDateKey(),wordRecords:readP1Records(englishWordRecordsKey),politicsRecords:readP1Records(politicsRecordsKey),professionalUnits:professional,outputRecords:readOutputRecords()});saveAnkiCandidates(generated,"p1-generate-anki");renderAnkiCandidates();}
function setAnkiCandidateStatus(cardId,status){if(!ANKI_STATUSES.includes(status))return;const records=readAnkiCandidates();const card=records.find(item=>item.cardId===cardId);if(!card)return;card.status=status;card.updatedAt=new Date().toISOString();saveAnkiCandidates(records);renderAnkiCandidates();}
function downloadAnki(format){const records=readAnkiCandidates();const approved=records.filter(item=>item.status==="approved");if(!approved.length)return setStatus("#ankiStatus","没有已批准候选。",true);const content=exportAnkiCandidates(approved,format,true);downloadFile(`anki-candidates-${getDateKey()}.${format}`,content,format==="json"?"application/json;charset=utf-8":"text/plain;charset=utf-8");const now=new Date().toISOString();approved.forEach(card=>{card.status="exported";card.exportedAt=now;card.updatedAt=now;});saveAnkiCandidates(records,"p1-export-anki");renderAnkiCandidates();}
function ensureAnkiPanel(){if(document.querySelector("#ankiPanel"))return;const panel=document.createElement("details");panel.id="ankiPanel";panel.className="panel low-frequency-panel";panel.innerHTML=`<summary><span><span class="step">Anki候选</span><strong>候选卡审核与导出</strong></span></summary><div class="low-frequency-body"><p class="muted">只生成候选，不连接Anki；批准后才能导出。</p><div class="button-row"><button id="generateAnkiBtn" class="button secondary" type="button">从今日结果生成候选</button><button data-anki-export="tsv" class="button ghost" type="button">导出TSV</button><button data-anki-export="csv" class="button ghost" type="button">导出CSV</button><button data-anki-export="json" class="button ghost" type="button">导出JSON</button><span id="ankiStatus" class="status"></span></div><div id="ankiCandidateList" class="professional-results-list"></div></div>`;document.querySelector("main.dashboard").appendChild(panel);panel.querySelector("#generateAnkiBtn").addEventListener("click",generateTodayAnkiCandidates);panel.querySelectorAll("[data-anki-export]").forEach(button=>button.addEventListener("click",()=>downloadAnki(button.dataset.ankiExport)));}
function renderAnkiCandidates(){const list=document.querySelector("#ankiCandidateList");if(!list)return;list.replaceChildren();const ranks={high:0,medium:1,low:2};const records=readAnkiCandidates().filter(item=>item.status!=="rejected").sort((a,b)=>(ranks[a.priority]??9)-(ranks[b.priority]??9));records.forEach(card=>{const row=document.createElement("article");row.className="professional-unit-row";const text=document.createElement("div");const title=document.createElement("strong");title.textContent=`${card.subject} · ${card.front}`;const meta=document.createElement("span");meta.textContent=`${card.priority}｜${card.status}｜${card.tags.join(" ")}`;text.append(title,meta);const actions=document.createElement("div");actions.className="button-row";[["approved","批准"],["rejected","拒绝"]].forEach(([status,label])=>{const button=document.createElement("button");button.type="button";button.className="button ghost";button.textContent=label;button.addEventListener("click",()=>setAnkiCandidateStatus(card.cardId,status));actions.appendChild(button);});row.append(text,actions);list.appendChild(row);});const pending=readAnkiCandidates().filter(item=>item.status==="candidate").length;const existing=document.querySelector("#ankiHomeSummary");if(existing)existing.textContent=`Anki待批准：${pending}`;}
function initP1Anki(){ensureAnkiPanel();if(!document.querySelector("#ankiHomeSummary")){const summary=document.createElement("p");summary.id="ankiHomeSummary";summary.className="muted";document.querySelector("#topPriorityList").insertAdjacentElement("afterend",summary);}renderAnkiCandidates();}
