import fs from "node:fs";
import assert from "node:assert/strict";

const tasksSource = fs.readFileSync(new URL("../js/tasks.js", import.meta.url), "utf8");
const workflowSource = fs.readFileSync(new URL("../docs/USER-WORKFLOW.md", import.meta.url), "utf8");
const executionStateSource = fs.readFileSync(new URL("../js/execution-state-core.js", import.meta.url), "utf8");
const reviewSource = fs.readFileSync(new URL("../js/review.js", import.meta.url), "utf8");

assert.match(tasksSource, /function getUnifiedTaskPrimary\(/);
assert.match(tasksSource, /"先做5分钟"/);
assert.match(tasksSource, /"继续刚才的5分钟"/);
assert.match(tasksSource, /"结束并记录"/);
assert.match(tasksSource, /"查看 \/ 更新记录"/);
assert.match(tasksSource, /function createTaskMoreActions\(/);
assert.match(tasksSource, /function getTaskRowPrimaryCommand\(/);
assert.match(tasksSource, /taskPrimaryCommandByButton\.set\(button, getTaskRowPrimaryCommand\(task, status, config\)\)/);
assert.match(tasksSource, /executionSurfaceCommandsMatch\(renderedPrimaryCommand, freshCommand\)/);
assert.match(tasksSource, /function renderTasks\(\)[\s\S]*description\.textContent = getTaskExecutionDescription\(task\)/);
assert.match(tasksSource, /appendP1ResultSummary\(task, content, body\)/);
assert.match(tasksSource, /appendProfessionalTaskSummary\(task, content, body\)/);
assert.match(tasksSource, /appendP1OutputSummary\(task, content, body\)/);
assert.match(tasksSource, /lifeSummary\.textContent = `生活安排（\$\{lifeRows\.length\}项）`/);
assert.match(tasksSource, /actionName === "unified-start"/);
assert.match(tasksSource, /actionName === "unified-record"/);
assert.match(tasksSource, /actionName === "unified-complete"/);
assert.match(tasksSource, /performUnifiedTaskAction\(task, action\.dataset\.taskAction\)/);
assert.match(tasksSource, /function getSafeguardExecutionSurfaceModel\(/);
assert.match(tasksSource, /function getDailyHandoffExecutionSurfaceModel\(/);
assert.match(tasksSource, /function renderExecutionSurface\(\)/);
assert.match(tasksSource, /function getExecutionSurfaceSnapshot\(\)/);
assert.match(tasksSource, /deriveExecutionSurfaceMode\(/);
assert.match(tasksSource, /function applyExecutionSurfaceView\(view\)/);
assert.match(tasksSource, /applyExecutionSurfaceView\(view\)/);
assert.match(executionStateSource, /FOCUS_PROTECTED: "focus-protected"[\s\S]*DEFAULT: "default"/);
assert.match(executionStateSource, /function createExecutionSurfaceView\(/);
assert.match(executionStateSource, /function createExecutionSurfaceCommand\(/);
assert.match(executionStateSource, /function executionSurfaceCommandsMatch\(/);
assert.match(executionStateSource, /function selectDailyGuidanceItem\(items, options = \{\}\)/);
assert.match(tasksSource, /selectDailyGuidanceItem\(items, \{ actionField: "tomorrowAction" \}\)/);
assert.match(reviewSource, /selectDailyGuidanceItem\(buildDailyExecutionGapItems\(plan\), \{/);
assert.match(tasksSource, /function executeExecutionSurfaceCommand\(snapshot\)/);
assert.match(tasksSource, /executionSurfaceCommandsMatch\(activeExecutionSurfaceSnapshot\?\.command, freshSnapshot\.command\)/);
assert.match(tasksSource, /function getDailyExecutionGapStartAction\(task\)/);
assert.match(tasksSource, /tomorrowAction: getDailyExecutionGapTomorrowAction\(task722,/);
assert.match(tasksSource, /function getSavedRecordedStartAction\(task\)/);
assert.match(tasksSource, /readP1Records\(englishReadingRecordsKey\)/);
assert.match(tasksSource, /readP1Records\(politicsRecordsKey\)/);
assert.match(tasksSource, /readOutputRecords\(\)/);
assert.match(tasksSource, /inferPlanOutputSubject\(task\)/);
assert.match(tasksSource, /record\.subject \|\| ""\) === subject/);
assert.match(tasksSource, /function getPlannedTaskStartAction\(task\)/);
assert.match(tasksSource, /normalizeTaskStartAction\(task\.nextStart\)/);
assert.match(tasksSource, /task\.manualEdited === true \? normalizeTaskStartAction\(task\.description\)/);
assert.match(tasksSource, /function getTaskStartContext\(task\)/);
assert.match(tasksSource, /承接 \$\{date\} 正式记录/);
assert.match(tasksSource, /function startResultHandoffNext\(\)/);
assert.match(tasksSource, /function getResultHandoffModel\(/);
assert.match(executionStateSource, /function createResultHandoffModel\(/);
assert.match(executionStateSource, /function resultHandoffModelsMatch\(/);
assert.match(executionStateSource, /left\.taskKey === right\.taskKey/);
assert.match(executionStateSource, /left\.displayKey === right\.displayKey/);
assert.match(tasksSource, /createResultHandoffModel\(\{/);
assert.match(tasksSource, /executionSnapshot\?\.command \|\| createExecutionSurfaceCommand\(null\)/);
assert.match(executionStateSource, /suppliedTaskId === commandTaskId/);
assert.match(executionStateSource, /const command = taskId \? \{ \.\.\.executionCommand, taskId \} : emptyCommand\(\)/);
assert.match(tasksSource, /executionLabel: executionSnapshot\?\.view\?\.primary\?\.label/);
assert.match(tasksSource, /executeExecutionSurfaceCommand\(freshModel\.executionSnapshot\)/);
assert.doesNotMatch(tasksSource.slice(tasksSource.indexOf("function startResultHandoffNext"), tasksSource.indexOf("function setTaskStatus")), /performUnifiedTaskAction/);
assert.match(executionStateSource, /!taskId[\s\S]*今日正式任务已完成；可以检查记录后收工/);
assert.match(workflowSource, /一个专业课闭卷产物.*英语最低动作.*政治最低动作.*两句话收工.*滚动复盘仅保留提醒和手动入口/s);
assert.match(workflowSource, /明日第一动作.*下一准确起点.*直接开始5分钟/s);
assert.match(workflowSource, /时间表.*下一项学习任务.*准确起点/s);
assert.match(workflowSource, /关键缺口.*晚间止损.*准确起点/s);
assert.match(workflowSource, /英语阅读.*政治.*专业课输出.*正式保存.*准确起点/s);
assert.match(workflowSource, /专业课输出.*722.*844.*无法明确.*原计划动作/s);
assert.match(workflowSource, /今日计划.*nextStart.*人工修改.*历史断点.*完成标准/s);
assert.match(workflowSource, /历史正式断点.*来源日期.*5分钟目标.*纯动作/s);
assert.match(workflowSource, /保存真实结果.*先做下一项5分钟.*点击后.*启动计时/s);
assert.match(workflowSource, /未结束专注.*保底模式.*昨日交接.*晚间收工.*关键缺口.*正常计划/s);
assert.match(workflowSource, /任务ID、标题、说明和主按钮.*同一个显示模型.*唯一函数/s);
assert.match(workflowSource, /点击驾驶舱主按钮.*重新核对.*状态已经变化.*不会继续执行过期动作/s);
assert.match(workflowSource, /展开今日时间表.*任务的主按钮.*同一套动作校验.*不会按旧按钮/s);
assert.match(workflowSource, /保存正式结果后.*先做下一项5分钟.*回执来源和下一任务命令.*不会启动旧任务/s);

assert.doesNotMatch(workflowSource, /Anki 候选|扫描欠账|分别记录单词/);
assert.match(workflowSource, /先做5分钟.*继续25分钟.*结束并记录.*自动完成/s);

console.log("UNIFIED_TASK_FLOW_TEST_OK");
